# Generated by Django 4.0.5 on 2022-10-01 10:12

import blogApp.models.image.image
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFileDir', models.CharField(default='none', max_length=55)),
                ('articleDir', models.CharField(default='none', max_length=85)),
                ('imageMaxSize', models.FloatField(blank=True, default=200.0, null=True)),
                ('imageCurrentSize', models.FloatField(blank=True, default=0.0, null=True)),
                ('avatarUrl', models.URLField(default='/images/avatar.jpg', max_length=256)),
                ('backgroundUrl', models.URLField(default='/images/backgroundimage.png', max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageName', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('imageFile', models.ImageField(upload_to=blogApp.models.image.image.imagePath, verbose_name='图片地址')),
                ('imageId', models.BigAutoField(primary_key=True, serialize=False)),
                ('imageCreateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('imageVisible', models.BooleanField(default=True)),
                ('imageUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.bloguser')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleId', models.BigAutoField(primary_key=True, serialize=False)),
                ('articleTitle', models.CharField(blank=True, default='', max_length=55, null=True)),
                ('articleContent', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('articleKeyWords', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('articleBrief', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('articleVisible', models.CharField(default='all', max_length=10)),
                ('articleCreateTime', models.DateTimeField(auto_now=True)),
                ('articleUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.bloguser')),
            ],
        ),
    ]
