# Generated by Django 4.0.5 on 2022-10-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_image_imagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatarUrl',
            field=models.URLField(default='http://150.158.182.65/static/images/avatar.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='backgroundUrl',
            field=models.URLField(default='', max_length=256),
        ),
    ]
