# Generated by Django 4.0.5 on 2022-10-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_bloguser_backgroundurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageFileName',
            field=models.CharField(default='', max_length=128, verbose_name='文件名字'),
        ),
    ]
