# Generated by Django 4.0.5 on 2022-11-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0008_image_imagethumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='avatarThumbnail',
            field=models.CharField(default='/media/images/2022100822521821.png', max_length=256),
        ),
    ]
