# Generated by Django 4.0.5 on 2022-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_alter_bloguser_avatarurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleType',
            field=models.CharField(default='文章', max_length=10),
        ),
    ]
