# Generated by Django 4.0.5 on 2022-10-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_article_articletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatarUrl',
            field=models.CharField(default='/media/images/2022100822521821.png', max_length=256),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='backgroundUrl',
            field=models.CharField(default='', max_length=256),
        ),
    ]
