# Generated by Django 4.0.5 on 2022-10-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_alter_bloguser_avatarurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='backgroundUrl',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
