# Generated by Django 4.0.5 on 2022-11-11 03:20

import blogApp.models.image.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_image_imagefilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageThumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=blogApp.models.image.image.thumbnailPath, verbose_name='缩略图'),
        ),
    ]
