# Generated by Django 4.0.5 on 2022-11-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0009_bloguser_avatarthumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatarThumbnail',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
